### ISSUE TITLE
How can IBM Cloudant data can be transferred to mongoDB?

### ISSUE THREAD

**Issue by jimishio** [jimishio/couchdb-to-mongodb#1]
As IBM Cloudant is also based on CouchDB, how IBM cloudant databases can be transferred to different collections of a single database or multiple databases.
Cloudant only gives maximum 200 documents per query.

**Comment by BhumiModi** [comment]
Sure. That is possible. 
Solution of the same has been updated in README.md with [commit](https://github.com/jimishio/couchdb-to-mongodb/commit/0ce7ec40bf2e465af49ab57dc3577e6839f531f1).
